### ISSUE TITLE
How does this compare to kotlinx-coroutines-android?

### ISSUE THREAD

**Issue by LouisCAD** [metalabdesign/AsyncAwait#20]
Hi,
I discovered JetBrains (and probably other contributors) made a coroutines Android implementation on the [kotlinx.couroutines](https://github.com/Kotlin/kotlinx.coroutines) repo, and I assume you were aware of this while building this library.

Could you add a word in the README.md or another file in the repo on how your implementation and the kotlinx one compare together in different regards such as performance, API design and features (and more if useful)?

**Comment by pilgr** [comment]
Sure! At the time when we started to build our solution, no other lib utilized coroutines. That was the main reason to play with coroutines for us. Recently Kotlin team added Android UI context support to the kotlinx.coroutines lib. I don't mind if we eventually discontinue our lib in favor of the official solution or make it compatible with kotlinx lib but for now, I have to take a closer look what the official solution is.
