### ISSUE TITLE
Question: Code execution sequence

### ISSUE THREAD

**Issue by curioustechizen** [metalabdesign/AsyncAwait#7]
Thanks for this library - it is really nice to see Async/Await coming to Android. I have a question about the sequence of execution. Consider this example

```kotlin
async {
   progressBar.visibility = View.VISIBLE
   // Release main thread and wait until text is loaded in background thread
   val loadedText = await { loadFromServer() }
   // Loaded successfully, come back in UI thread and show the result
   txtResult.text = loadedText
   progressBar.visibility = View.INVISIBLE
}
someOtherCodeHere()
yetMoreAwesomeCodeHere()
```

I understand that when we hit `await { loadFromServer() }`, the execution of the `async` block is suspended and the control proceeds to `someOtherCodeHere()`. Is this right?

Also, what happens later when `loadFromServer()` returns? I assume then `txtResult.text = loadedText` and the rest of the `async` block is executed. But, then what? Where does the execution proceed after an async block that had been suspended is un-suspended?

**Comment by pilgr** [comment]
Your assumptions are absolutely correct. Code control proceeds to the code following after `async` block as soon as we hit suspension point (`await` is called). When `loadFromServer()` returns the rest of coroutine (code inside `async` block) continues execution. Formally, it's just like posting lambda with rest of coroutine to a `Handler` to execute in UI thread
```
val loadedText = ...
mHandler.post {
   txtResult.text = loadedText
   progressBar.visibility = View.INVISIBLE
}
```

**Comment by curioustechizen** [comment]
The analogy with a lambda helps in understanding it. Thanks!
